channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.2
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.3.2
  - pyarrow==15.0.2
  - pyyaml==6.0.2
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
